//
//  sanlegasViewController.swift
//  VIPERCHIDO
//
//  Created ISAAC DAVID SANTIAGO on 14/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class sanlegasViewController: UIViewController, sanlegasViewProtocol {

	var presenter: sanlegasPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
