//
//  sanlegasInteractor.swift
//  VIPERCHIDO
//
//  Created ISAAC DAVID SANTIAGO on 14/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class sanlegasInteractor: sanlegasInteractorProtocol {

    weak var presenter: sanlegasPresenterProtocol?
}
