# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'RemoteControl' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift', '> 7.0-beta'
  pod 'Firebase/Auth'
  pod 'SSSpinnerButton'
  
  # Pods for RemoteControl

  target 'RemoteControlTests' do
    inherit! :search_paths
  end
end
