//
//  devicesProtocols.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 21/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

protocol ViewToPresenterDevicesProtocol: AnyObject{
    var view:PresenterToViewDevicesProtocol? {get set}
    var interactor: PresenterToViewDevicesProtocol? {get set}
    var router: PresenterToRouterDevicesProtocol? {get set}
}

protocol PresenterToViewDevicesProtocol:AnyObject {
    
}

protocol InteractorToPresenterDevicesProtocol: AnyObject {
    
}

protocol PresenterToInteractorDevicesProtocol: AnyObject{
    
}

protocol PresenterToRouterDevicesProtocol: AnyObject{
    
}
