//
//  devicesRouter.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 21/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DevicesRouter: PresenterToRouterDevicesProtocol {

    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {

        let view = DevicesViewController(nibName: "DevicesViewController", bundle: Bundle(for: DevicesRouter.self))
        
        let interactor = DevicesInteractor()
        let router = DevicesRouter()
        let presenter : ViewToPresenterDevicesProtocol & InteractorToPresenterDevicesProtocol = DevicesPresenter()
        
        view.presenter = presenter
        view.presenter?.view = view
        view.presenter?.interactor = interactor
        view.presenter?.router = router
        
        return view
    }
    
    func redirecScreenView(on view: PresenterToViewDevicesProtocol,with device: Device) {
        let screenRouter = ScreenDisplayRouter.createModule(with: device)
        let vc = view as! DevicesViewController
        vc.navigationController?.pushViewController(screenRouter, animated: true)
    }
    
    
    
}
