//
//  devicesPresenter.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 21/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DevicesPresenter: ViewToPresenterDevicesProtocol {

    

    var view: PresenterToViewDevicesProtocol?
    
    var interactor: PresenterToInteractorDevicesProtocol?
    
    var router: PresenterToRouterDevicesProtocol?
    
    func getDevicesByCurrentUser(success: @escaping ([Device]) -> (), failure: @escaping () -> ()) {
        interactor?.getDevicesByCurrentUser(success: { devices in
            success(devices)
        }, failure: {
            failure()
        })
    }
    func redirectScrenDisplay() {
        router?.redirecScreenView(on: view!)
    }
}

extension DevicesPresenter: InteractorToPresenterDevicesProtocol{
    
}
