//
//  devicesViewController.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 21/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import FirebaseAuth

class DevicesViewController: UIViewController {
    
    var presenter: ViewToPresenterDevicesProtocol?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
    }
    

    @IBAction func cerrarSesiom(_ sender: Any) {
        do {
          try Auth.auth().signOut()
        } catch let signOutError as NSError {
          print("Error signing out: %@", signOutError)
        }
    }
}
