//
//  devicesInteractor.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 21/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DevicesInteractor: devicesInteractorProtocol {

    weak var presenter: devicesPresenterProtocol?
}
