//
//  devicesInteractor.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 21/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DevicesInteractor: PresenterToInteractorDevicesProtocol {
    let firebaseClient = FirebaseClient()

    func getDevicesByCurrentUser(success: @escaping (_ devices: [Device]) -> (), failure:@escaping() -> () ) {
        firebaseClient.getDevicesByCurrentUser { devices in
            success(devices)
        } failure: {
            failure()
        }

    }
    
}
