//
//  sanlegasProtocols.swift
//  VIPERSTORYBOARD
//
//  Created ISAAC DAVID SANTIAGO on 14/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol sanlegasWireframeProtocol: class {

}
//MARK: Presenter -
protocol sanlegasPresenterProtocol: class {

}

//MARK: Interactor -
protocol sanlegasInteractorProtocol: class {

  var presenter: sanlegasPresenterProtocol?  { get set }
}

//MARK: View -
protocol sanlegasViewProtocol: class {

  var presenter: sanlegasPresenterProtocol?  { get set }
}
