//
//  sanlegasPresenter.swift
//  VIPERSTORYBOARD
//
//  Created ISAAC DAVID SANTIAGO on 14/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class sanlegasPresenter: sanlegasPresenterProtocol {

    weak private var view: sanlegasViewProtocol?
    var interactor: sanlegasInteractorProtocol?
    private let router: sanlegasWireframeProtocol

    init(interface: sanlegasViewProtocol, interactor: sanlegasInteractorProtocol?, router: sanlegasWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
