//
//  loginProtocols.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 16/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

protocol PresenterToViewLoginProtocol: AnyObject {
    
}

protocol ViewToPresenterLoginProtocol: AnyObject {
    var view: PresenterToViewLoginProtocol? {get set}
    var router: PresenterToRouterLoginProtocol? {get set}
    var interactor: PresenterToInteractorLoginProtocol? {get set}
    func login(user:String ,
                    password:String ,
                    success: @escaping() -> () ,
                    failure: @escaping() -> ())
    func redirecDevicesView()
}

protocol PresenterToInteractorLoginProtocol: AnyObject {
    func login(user:String ,
                    password:String ,
                    success: @escaping() -> () ,
                    failure: @escaping() -> ())
}

protocol InteractorToPresenterLoginProtocol: AnyObject {

}

protocol PresenterToRouterLoginProtocol: AnyObject {

    func redirecDevicesView(on view: PresenterToViewLoginProtocol)
}
