//
//  loginViewController.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 16/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import FirebaseAuth
import SSSpinnerButton

class LoginViewController: UIViewController {

    @IBOutlet weak var usuarioText: UITextField!
    @IBOutlet weak var passwordText: UITextField!
    
    @IBOutlet weak var iniciarSesionButton: SSSpinnerButton!
    var presenter: ViewToPresenterLoginProtocol?
    let labelButton = "Iniciar Sesión"
    
    func showMessageError(){
        let uialert = UIAlertController(title: "Error al loguearse", message: "Los datos introducidos son incorrectos", preferredStyle: UIAlertController.Style.alert)
            uialert.addAction(UIAlertAction(title: "Ok", style: UIAlertAction.Style.default, handler: nil))
            self.present(uialert, animated: true, completion: nil)
        stopAnimationButton()
    }
    
    func stopAnimationButton(){
        iniciarSesionButton.stopAnimate(complete: {
            self.iniciarSesionButton.setTitle(self.labelButton, for: UIControl.State.normal)
        })
    }
	override func viewDidLoad() {
        super.viewDidLoad()

    }
    
    func changeView(){
        presenter?.redirecDevicesView()

    }

    @IBAction func iniciarSesionClick(_ sender: Any) {
        
        iniciarSesionButton.startAnimate(spinnerType: SpinnerType.ballClipRotate, spinnercolor: UIColor.red, spinnerSize: 20, complete: { [self] in
            self.iniciarSesionButton.setTitle("", for: UIControl.State.normal)
            presenter?.login(user: self.usuarioText.text!, password:  self.passwordText.text!, success: {
                self.stopAnimationButton()
                self.changeView()
            }, failure: {
                self.showMessageError()
                self.changeView()
            })
            
        })
        


    }
}

extension LoginViewController: PresenterToViewLoginProtocol {
    
}
