//
//  loginRouter.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 16/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginRouter: PresenterToRouterLoginProtocol {
        
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = LoginViewController(nibName: nil, bundle: nil)
        let interactor = LoginInteractor()
        let router = LoginRouter()
        let presenter: ViewToPresenterLoginProtocol & InteractorToPresenterLoginProtocol
                = LoginPresenter()
        
        view.presenter = presenter
        view.presenter?.view = view
        view.presenter?.interactor = interactor
        view.presenter?.router = router
        
        return view
    }
    
    func redirecDevicesView(on view: PresenterToViewLoginProtocol){
        let devicesRouter = DevicesRouter.createModule()
        let vc = view as! LoginViewController
       
        vc.navigationController?.pushViewController(devicesRouter, animated: true)
    }
}
