//
//  loginPresenter.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 16/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginPresenter: ViewToPresenterLoginProtocol {

    
    var view: PresenterToViewLoginProtocol?
    
    var router: PresenterToRouterLoginProtocol?
    
    var interactor: PresenterToInteractorLoginProtocol?
        
    func login(user:String ,
                    password:String ,
                    success: @escaping() -> () ,
                    failure: @escaping() -> ()){
        interactor?.login(user: user, password: password) {
            success()
        } failure: {
            failure()
        }
        
    }
    
    func redirecDevicesView() {
        router?.redirecDevicesView(on: view!)
    }
}

extension LoginPresenter: InteractorToPresenterLoginProtocol {
    
}
