//
//  loginInteractor.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 16/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginInteractor: PresenterToInteractorLoginProtocol {

    weak var presenter: InteractorToPresenterLoginProtocol?
    let firebaseClient = FirebaseClient()
    
    func login(user:String ,
                    password:String ,
                    success: @escaping() -> () ,
                    failure: @escaping() -> ()){
        firebaseClient.login(user: user, password: password) {
            success()
        } failure: {
            failure()
        }
        
    }
    
    
    
}
