//
//  pruebaModuloRouter.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 30/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class pruebaModuloRouter: pruebaModuloWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = pruebaModuloViewController(nibName: nil, bundle: nil)
        let interactor = pruebaModuloInteractor()
        let router = pruebaModuloRouter()
        let presenter = pruebaModuloPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
