//
//  pruebaModuloProtocols.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 30/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol pruebaModuloWireframeProtocol: class {

}
//MARK: Presenter -
protocol pruebaModuloPresenterProtocol: class {

    var interactor: pruebaModuloInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol pruebaModuloInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol pruebaModuloInteractorInputProtocol: class {

    var presenter: pruebaModuloInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol pruebaModuloViewProtocol: class {

    var presenter: pruebaModuloPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
