//
//  pruebaModuloPresenter.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 30/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class pruebaModuloPresenter: pruebaModuloPresenterProtocol, pruebaModuloInteractorOutputProtocol {

    weak private var view: pruebaModuloViewProtocol?
    var interactor: pruebaModuloInteractorInputProtocol?
    private let router: pruebaModuloWireframeProtocol

    init(interface: pruebaModuloViewProtocol, interactor: pruebaModuloInteractorInputProtocol?, router: pruebaModuloWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
