//
//  pruebaModuloViewController.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 30/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class pruebaModuloViewController: UIViewController, pruebaModuloViewProtocol {

	var presenter: pruebaModuloPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
