//
//  ScreenDisplayRouter.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 11/07/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ScreenDisplayRouter: ScreenDisplayWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        //let view = ScreenDisplayViewController(nibName: nil, bundle: nil)
        let view = ScreenDisplayViewController(nibName: "ScreenDisplayViewController", bundle: Bundle(for: ScreenDisplayRouter.self))

        let interactor = ScreenDisplayInteractor()
        let router = ScreenDisplayRouter()
        let presenter: ScreenDisplayPresenterProtocol & ScreenDisplayInteractorOutputProtocol = ScreenDisplayPresenter()

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    

}
