//
//  ScreenDisplayInteractor.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 11/07/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ScreenDisplayInteractor: PresenterToInteractorScreenDisplayProtocol {

    
    var presenter: InteractorToPresenterScreenDisplayProtocol?
    let firebaseClient = FirebaseClient()

    func getScreenFromIdDevice(idDevice:String,
                               success: @escaping(_ screen: Data) -> () ,
                               failure: @escaping() -> ()){
        firebaseClient.getScreenFromIdDevice(idDevice: idDevice) { screen in
            success(screen)
        } failure: {
            failure()
        }

    }
    
    
    func handleScreenDevice(deviceId: String, lastUpdated: Any, success: @escaping (Data) -> (), failure: @escaping () -> ()) {
        firebaseClient.handleScreenDevice(deviceId: deviceId, lastUpdated: lastUpdated) { screenCapture in
            success(screenCapture)
        } failure: {
            failure()
        }

    }
    
}
