//
//  ScreenDisplayProtocols.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 11/07/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ScreenDisplayWireframeProtocol: class {

}
//MARK: Presenter -
protocol ScreenDisplayPresenterProtocol: class {

    var interactor: ScreenDisplayInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol ScreenDisplayInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol ScreenDisplayInteractorInputProtocol: class {

    var presenter: ScreenDisplayInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol ScreenDisplayViewProtocol: class {

    var presenter: ScreenDisplayPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
