//
//  ScreenDisplayRouter.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 11/07/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ScreenDisplayRouter: PresenterToRouterScreenDisplayProtocol {

    weak var viewController: UIViewController?

    static func createModule(with device: Device) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        //let view = ScreenDisplayViewController(nibName: nil, bundle: nil)
        let view = ScreenDisplayViewController(nibName: "ScreenDisplayViewController", bundle: Bundle(for: ScreenDisplayRouter.self))

        let interactor = ScreenDisplayInteractor()
        let router = ScreenDisplayRouter()
        let presenter: ViewToPresenterScreenDisplayProtocol & InteractorToPresenterScreenDisplayProtocol = ScreenDisplayPresenter()

        view.deviceId = device.uid
        view.lastUpdated = device.lastUpdate
        view.presenter = presenter
        view.presenter?.view = view
        view.presenter?.interactor = interactor
        view.presenter?.router = router
        
        return view
    }
    

}
