//
//  ScreenDisplayPresenter.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 11/07/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ScreenDisplayPresenter: ScreenDisplayPresenterProtocol, ScreenDisplayInteractorOutputProtocol {

    weak private var view: ScreenDisplayViewProtocol?
    var interactor: ScreenDisplayInteractorInputProtocol?
    var router: ScreenDisplayWireframeProtocol?


}
