//
//  registerRouter.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 20/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class registerRouter: registerWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = registerViewController(nibName: nil, bundle: nil)
        let interactor = registerInteractor()
        let router = registerRouter()
        let presenter = registerPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
