//
//  registerPresenter.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 20/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class registerPresenter: registerPresenterProtocol {

    weak private var view: registerViewProtocol?
    var interactor: registerInteractorProtocol?
    private let router: registerWireframeProtocol

    init(interface: registerViewProtocol, interactor: registerInteractorProtocol?, router: registerWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
