//
//  registerViewController.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 20/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class registerViewController: UIViewController, registerViewProtocol {

	var presenter: registerPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
