//
//  registerProtocols.swift
//  RemoteControl
//
//  Created ISAAC DAVID SANTIAGO on 20/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol registerWireframeProtocol: class {

}
//MARK: Presenter -
protocol registerPresenterProtocol: class {

}

//MARK: Interactor -
protocol registerInteractorProtocol: class {

  var presenter: registerPresenterProtocol?  { get set }
}

//MARK: View -
protocol registerViewProtocol: class {

  var presenter: registerPresenterProtocol?  { get set }
}
